### ISSUE TITLE
max / min regridding method high to coarse resolution

### ISSUE THREAD

**Issue by folmerkrikken** [xarray-contrib/xarray-regrid#35]
Hi, thanks for this great package. I really like how easy it is to use. It can definitely take over some of the use cases where I now still use XESMF / CDO. I was wondering if it would be possible to add a max and min regridding method just like remapmax and remapmin in CDO ( ds.regrid.max / ds.regrid.min ) when regridding high res data to low res data.

Thanks, Folmer

**Comment by BSchilperoort** [comment]
Hi Folmer, good to hear that you're enjoying using xarray-regrid. I think adding a min/max method should be relatively easy to implement. 
Other statistics such as the variance or standard deviation will be difficult to implement though.

**Comment by slevang** [comment]
This is available with `regrid.stat` now (#46).
